# ArizenOS Funding
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: []
patreon: arizenos
open_collective: arizenos
ko_fi: arizenos
custom:
  - https://arizenos.dev/sponsor
