title: Create System Restore Point
actions:
  - !powerShell:
      wait: true
      command: >-
        Enable-ComputerRestore -Drive 'C:\' -ErrorAction SilentlyContinue;
        Checkpoint-Computer -Description 'ArizenOS Pre-Install' -RestorePointType MODIFY_SETTINGS
