title: Enable Transparency and Acrylic Effects
actions:
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'EnableTransparency', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'EnableBlurBehind', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\DWM', value: 'Composition', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\DWM', value: 'GlassOpacity', type: REG_DWORD, data: '85'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\DWM', value: 'ColorizationBlurBalance', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'UseOLEDTaskbarTransparency', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarTranslucent', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ImmersiveShell', value: 'UseAcrylicSurface', type: REG_DWORD, data: '1'}
  - !registryValue: {path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize', value: 'EnableMicaEffect', type: REG_DWORD, data: '1'}
